<?php

namespace Elpiafo\SwitchUserBundle\Repository;

/**
 * SwitchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SwitchRepository extends \Doctrine\ORM\EntityRepository
{
}
